### ISSUE TITLE
Decide the specification of PLATEAU architecture

### ISSUE THREAD

**Issue by HideBa** [eukarya-inc/reearth-plateauview#24]
# Todo
- [ ] Decide the architecture of PLATEAU back-end
	- [ ] list up use cases which describe how it'll be mainly used by each actor
	- [ ] API interface
	- [ ] draw a sequence diagram of each use case
- [ ] Decide how the plugins will interact with PLATEAU, Re:Earth, and CMS back-end
- [ ] Check if all can satisfy these requirements
	- [ ] Save and deliver sidebar settings
	- [ ] Save and deliver shorten URLs and their data
	- [ ] API to get CityGML file URLs by mesh code for SDK
	- [ ] Reverse proxy for `plateauview.jp`
	- [ ] CMS integration: communication with FME server
	- [ ] Uploading data to G空間情報センター
