### ISSUE TITLE
Map setting widget - Requirements

### ISSUE THREAD

**Issue by nina992** [eukarya-inc/reearth-plateauview#25]
###  **Todo**

-  Create widget plug-in to show map setting and modify them
-  The map settings that will be displayed are : 

1.   Map view : 
      - [ ] Choose between ( 3D Terrain - 3D smooth - 2D)
      - [ ] Check box to define whether Terrain hides the underground features 
     
2.    Base Map 

3.    Image optimization
      - [ ] Checkbox to check if always show or not 
5.    Raster Map Quality
      - [ ] Range slider between quality and performance 

![image](https://user-images.githubusercontent.com/89770889/179356268-e7978de7-5234-4718-b607-268b7863fe6d.png)

 ### Design 
![image](https://user-images.githubusercontent.com/89770889/179688320-278bba48-662e-451a-b17e-190ce607736b.png)

**Comment by lavalse** [comment]
Hey, @nina992 I changed a little bit of design for the map setting. 
![image](https://user-images.githubusercontent.com/3818046/179647194-7d8faece-1fc4-41a6-874a-072295795932.png)
We don't need to set the timeline plugin open or not here.

**Comment by lavalse** [comment]
And also, one of the main feature we have here is the sider-bar will have a different UI based on whether it is inside the Re:Earth editor . Please check [here](https://www.figma.com/file/xWM8xrtIAh5oMj0seLd9Jd/view-2.0?node-id=534%3A63367).
About the detail of tech. I guess we still need to discuss more.

**Comment by lavalse** [comment]
And also I m not sure why there is a **Enter the basement** checkbox in your screenshot. Because on my PC it looks like 
![image](https://user-images.githubusercontent.com/3818046/179647848-9129552c-d3b8-4324-b635-3d7adaa26f8c.png)
No that checkbox 😄. What happened ...

**Comment by airslice** [comment]
@lavalse If you use chome `translate to English` then it will be translated as `enter the basement`.

**Comment by nina992** [comment]
@lavalse  yes if I translate the page it shows this enter basement check box  , what is the right translation

**Comment by lavalse** [comment]
@nina992 okok, I see. I also don't what that check does. Let's me check a little bit. 😄

**Comment by lavalse** [comment]
OH. I see. It allows users to zoom in and can get into the earth. Then the land will become the sky. So funny. I think we don't need to support now. So ignore it now, please
